FW[144] Encoder abstraction on VMCU
HyperloopUPV-H8/VirtualMCU pull request #21
Opened 2024-12-26 01:47 UTC by jdmarmen

Added EncoderSensor implementation + small fixes in Encoder.py

EncoderSensor write() function gets a desired speed and acceleration and calculates the amount of ticks that the encoder generates so as to achieve that speed. It also calculates the position depending on the counter.

2024-12-28 15:00 UTC, jmaralo requested changes

2024-12-28 15:00 UTC, jmaralo commented on sensors/EncoderSensor.py
> +            raise self.EncoderSensorException()
use the convention of generate_speed for this function name, and also add a function that creates an input to set the counter to an arbitrary value

2025-01-04 13:25 UTC, jorgesg82 commented on sensors/EncoderSensor.py
> +        self.acceleration=0.0
What is acceleration used for? It doesn't seems to be used anywhere

2025-01-04 13:27 UTC, jorgesg82 commented on sensors/EncoderSensor.py
> +        self.acceleration=0.0
What is acceleration used for? It doesn't seem to be used anywhere

2025-01-04 14:10 UTC, jdmarmen commented on sensors/EncoderSensor.py
> +        self.acceleration=0.0
Yep, it has no functionality, was there just in case we needed to hard-code it and add a getter or something like that just for consulting, as it is now, it's not relevant.

2025-01-06 09:18 UTC, jorgesg82 approved these changes

2025-01-11 19:37 UTC, jmaralo approved these changes

2025-01-11 19:37 UTC, jmaralo commented on sensors/EncoderSensor.py
> +            raise self.EncoderSensorException()
Same as with linear sensor, this check should be done by the `Checked` input, because the user might prepare the input and apply it later during execution, and in that time the state might have changed

2025-01-11 19:37 UTC, jmaralo requested changes
Previous approve was a miss input, a miss input :(

2025-01-11 19:38 UTC, jmaralo commented on sensors/EncoderSensor.py
> +            raise self.EncoderSensorException()
notice, this is also in the generate_counter function

2025-01-12 15:05 UTC, jmaralo approved these changes

2025-01-12 15:11 UTC, g0nz4I0 approved these changes

2025-01-12 15:11 UTC, merged